-- ============================================================
-- Hoxiee — Question bank seed data
-- Auto-generated from questions.json (1000 questions)
-- Run this in: Supabase Dashboard → SQL Editor → New query
-- Safe to re-run: uses ON CONFLICT to upsert existing rows.
-- ============================================================

create table if not exists public.quiz_questions (
  id integer primary key,
  subject text not null,
  category text not null,
  prompt text not null,
  answer text not null,
  unique (subject, category, id)
);

alter table public.quiz_questions enable row level security;

-- ============================================================
-- Math · Algebra (334 questions)
-- ============================================================
insert into public.quiz_questions (id, subject, category, prompt, answer) values
  (1001, 'math', 'algebra', '2x + 2 = 18', '8'),
  (1002, 'math', 'algebra', '2x - 2 = 28', '15'),
  (1003, 'math', 'algebra', '2x - 3 = 21', '12'),
  (1004, 'math', 'algebra', '2x - 1 = 15', '8'),
  (1005, 'math', 'algebra', '2(x + 1) = 18', '8'),
  (1006, 'math', 'algebra', '2x + 5 = 7', '1'),
  (1007, 'math', 'algebra', '2(x - 1) = 8', '5'),
  (1008, 'math', 'algebra', '2(x + 2) = 18', '7'),
  (1009, 'math', 'algebra', '2(x + 2) = 8', '2'),
  (1010, 'math', 'algebra', '2(x + 2) = 14', '5'),
  (1011, 'math', 'algebra', '2x + 4 = 16', '6'),
  (1012, 'math', 'algebra', '2x + 2 = 4', '1'),
  (1013, 'math', 'algebra', '2x + 4 = 24', '10'),
  (1014, 'math', 'algebra', '2(x - 1) = 4', '3'),
  (1015, 'math', 'algebra', '2x + 1 = 7', '3'),
  (1016, 'math', 'algebra', '2(x - 2) = 8', '6'),
  (1017, 'math', 'algebra', '2x - 1 = 9', '5'),
  (1018, 'math', 'algebra', '2(x - 1) = 26', '14'),
  (1019, 'math', 'algebra', '2(x + 1) = 14', '6'),
  (1020, 'math', 'algebra', '2x + 4 = 26', '11'),
  (1021, 'math', 'algebra', '2(x + 2) = 26', '11'),
  (1022, 'math', 'algebra', '2x + 4 = 12', '4'),
  (1023, 'math', 'algebra', '2(x + 2) = 12', '4'),
  (1024, 'math', 'algebra', '2x + 1 = 3', '1'),
  (1025, 'math', 'algebra', '2x + 2 = 16', '7'),
  (1026, 'math', 'algebra', '2x - 1 = 37', '19'),
  (1027, 'math', 'algebra', '2x - 2 = 24', '13'),
  (1028, 'math', 'algebra', '2(x - 2) = 6', '5'),
  (1029, 'math', 'algebra', '2x + 2 = 20', '9'),
  (1030, 'math', 'algebra', '2x + 3 = 21', '9'),
  (1031, 'math', 'algebra', '2(x + 1) = 24', '11'),
  (1032, 'math', 'algebra', '2x - 2 = 10', '6'),
  (1033, 'math', 'algebra', '2x - 3 = 11', '7'),
  (1034, 'math', 'algebra', '2x - 3 = 31', '17'),
  (1035, 'math', 'algebra', '2(x + 2) = 6', '1'),
  (1036, 'math', 'algebra', '2x - 2 = 20', '11'),
  (1037, 'math', 'algebra', '2x + 1 = 9', '4'),
  (1038, 'math', 'algebra', 'x / 2 = 3', '6'),
  (1039, 'math', 'algebra', '2x - 1 = 31', '16'),
  (1040, 'math', 'algebra', '2x + 3 = 25', '11'),
  (1041, 'math', 'algebra', '2x - 1 = 17', '9'),
  (1042, 'math', 'algebra', '2x + 2 = 10', '4'),
  (1043, 'math', 'algebra', '2(x + 1) = 26', '12'),
  (1044, 'math', 'algebra', '2x - 2 = 38', '20'),
  (1045, 'math', 'algebra', '2x - 3 = 17', '10'),
  (1046, 'math', 'algebra', '2x - 1 = 39', '20'),
  (1047, 'math', 'algebra', '2x - 3 = 33', '18'),
  (1048, 'math', 'algebra', '2x - 2 = 6', '4'),
  (1049, 'math', 'algebra', '2x - 1 = 19', '10'),
  (1050, 'math', 'algebra', '2x - 2 = 4', '3'),
  (1051, 'math', 'algebra', '2x - 3 = 23', '13'),
  (1052, 'math', 'algebra', 'x / 2 = 12', '24'),
  (1053, 'math', 'algebra', 'x / 3 = 5', '15'),
  (1054, 'math', 'algebra', '2x - 2 = 2', '2'),
  (1055, 'math', 'algebra', '2x + 2 = 14', '6'),
  (1056, 'math', 'algebra', '2(x + 1) = 12', '5'),
  (1057, 'math', 'algebra', 'x / 2 = 14', '28'),
  (1058, 'math', 'algebra', '2x - 1 = 33', '17'),
  (1059, 'math', 'algebra', '2(x - 1) = 6', '4'),
  (1060, 'math', 'algebra', '2x + 3 = 11', '4'),
  (1061, 'math', 'algebra', 'x / 2 = 10', '20'),
  (1062, 'math', 'algebra', '2x - 2 = 16', '9'),
  (1063, 'math', 'algebra', '2x + 2 = 8', '3'),
  (1064, 'math', 'algebra', 'x / 2 = 11', '22'),
  (1065, 'math', 'algebra', '2x + 3 = 15', '6'),
  (1066, 'math', 'algebra', 'x / 2 = 4', '8'),
  (1067, 'math', 'algebra', '2x - 2 = 22', '12'),
  (1068, 'math', 'algebra', '2x - 1 = 13', '7'),
  (1069, 'math', 'algebra', '2(x - 1) = 2', '2'),
  (1070, 'math', 'algebra', '2x + 1 = 11', '5'),
  (1071, 'math', 'algebra', '2x - 3 = 35', '19'),
  (1072, 'math', 'algebra', '2(x - 1) = 18', '10'),
  (1073, 'math', 'algebra', '2x + 4 = 22', '9'),
  (1074, 'math', 'algebra', '2(x - 2) = 14', '9'),
  (1075, 'math', 'algebra', '2(x + 2) = 10', '3'),
  (1076, 'math', 'algebra', '2(x + 1) = 30', '14'),
  (1077, 'math', 'algebra', '2x - 3 = 25', '14'),
  (1078, 'math', 'algebra', '2(x - 1) = 12', '7'),
  (1079, 'math', 'algebra', '2(x + 1) = 20', '9'),
  (1080, 'math', 'algebra', '2x + 3 = 23', '10'),
  (1081, 'math', 'algebra', '2(x + 1) = 4', '1'),
  (1082, 'math', 'algebra', '2x + 2 = 24', '11'),
  (1083, 'math', 'algebra', '2(x + 1) = 8', '3'),
  (1084, 'math', 'algebra', '2(x + 1) = 16', '7'),
  (1085, 'math', 'algebra', '2x + 1 = 21', '10'),
  (1086, 'math', 'algebra', '2x - 2 = 36', '19'),
  (1087, 'math', 'algebra', '2x + 4 = 8', '2'),
  (1088, 'math', 'algebra', '2x - 3 = 3', '3'),
  (1089, 'math', 'algebra', '2(x + 1) = 28', '13'),
  (1090, 'math', 'algebra', '2x - 1 = 1', '1'),
  (1091, 'math', 'algebra', '2x - 1 = 5', '3'),
  (1092, 'math', 'algebra', '2x + 2 = 22', '10'),
  (1093, 'math', 'algebra', 'x / 2 = 8', '16'),
  (1094, 'math', 'algebra', '2x - 2 = 34', '18'),
  (1095, 'math', 'algebra', '2(x + 1) = 6', '2'),
  (1096, 'math', 'algebra', '2(x - 2) = 4', '4'),
  (1097, 'math', 'algebra', 'x / 3 = 3', '9'),
  (1098, 'math', 'algebra', '2x + 2 = 6', '2'),
  (1099, 'math', 'algebra', '2x - 3 = 37', '20'),
  (1100, 'math', 'algebra', 'x / 3 = 2', '6'),
  (1101, 'math', 'algebra', '2(x + 2) = 22', '9'),
  (1102, 'math', 'algebra', '2x - 3 = 29', '16'),
  (1103, 'math', 'algebra', '2x + 3 = 19', '8'),
  (1104, 'math', 'algebra', '2x - 3 = 1', '2'),
  (1105, 'math', 'algebra', '2(x + 1) = 10', '4'),
  (1106, 'math', 'algebra', '2(x - 1) = 20', '11'),
  (1107, 'math', 'algebra', '2x - 3 = 13', '8'),
  (1108, 'math', 'algebra', '2(x - 1) = 10', '6'),
  (1109, 'math', 'algebra', '2x - 2 = 18', '10'),
  (1110, 'math', 'algebra', '2x - 1 = 3', '2'),
  (1111, 'math', 'algebra', 'x / 2 = 9', '18'),
  (1112, 'math', 'algebra', '2x - 2 = 30', '16'),
  (1113, 'math', 'algebra', '2x - 2 = 32', '17'),
  (1114, 'math', 'algebra', 'x / 2 = 5', '10'),
  (1115, 'math', 'algebra', '2x + 4 = 14', '5'),
  (1116, 'math', 'algebra', '2(x - 2) = 16', '10'),
  (1117, 'math', 'algebra', '2x + 1 = 23', '11'),
  (1118, 'math', 'algebra', '2x - 1 = 7', '4'),
  (1119, 'math', 'algebra', 'x / 3 = 4', '12'),
  (1120, 'math', 'algebra', '2x + 2 = 12', '5'),
  (1121, 'math', 'algebra', '2x - 2 = 8', '5'),
  (1122, 'math', 'algebra', '2x - 1 = 27', '14'),
  (1123, 'math', 'algebra', '2x - 3 = 19', '11'),
  (1124, 'math', 'algebra', '2x + 1 = 13', '6'),
  (1125, 'math', 'algebra', 'x / 2 = 2', '4'),
  (1126, 'math', 'algebra', '2x + 4 = 6', '1'),
  (1127, 'math', 'algebra', '2x - 2 = 26', '14'),
  (1128, 'math', 'algebra', '2x - 3 = 9', '6'),
  (1129, 'math', 'algebra', '2x - 3 = 15', '9'),
  (1130, 'math', 'algebra', '2x + 3 = 9', '3'),
  (1131, 'math', 'algebra', '2x - 3 = 27', '15'),
  (1132, 'math', 'algebra', '2(x - 1) = 16', '9'),
  (1133, 'math', 'algebra', '2(x - 2) = 2', '3'),
  (1134, 'math', 'algebra', '2x - 3 = 5', '4'),
  (1135, 'math', 'algebra', '2(x - 1) = 24', '13'),
  (1136, 'math', 'algebra', '2x + 4 = 18', '7'),
  (1137, 'math', 'algebra', '2(x + 2) = 20', '8'),
  (1138, 'math', 'algebra', '2x - 3 = 7', '5'),
  (1139, 'math', 'algebra', '2(x - 1) = 22', '12'),
  (1140, 'math', 'algebra', '2x + 4 = 20', '8'),
  (1141, 'math', 'algebra', '2x + 1 = 5', '2'),
  (1142, 'math', 'algebra', '2x - 2 = 14', '8'),
  (1143, 'math', 'algebra', 'x / 2 = 13', '26'),
  (1144, 'math', 'algebra', '2x - 1 = 23', '12'),
  (1145, 'math', 'algebra', 'x / 2 = 6', '12'),
  (1146, 'math', 'algebra', '2(x - 1) = 28', '15'),
  (1147, 'math', 'algebra', '2x - 1 = 11', '6'),
  (1148, 'math', 'algebra', '2(x + 2) = 24', '10'),
  (1149, 'math', 'algebra', '2(x - 2) = 12', '8'),
  (1150, 'math', 'algebra', '2(x + 1) = 22', '10'),
  (1151, 'math', 'algebra', '2x - 1 = 29', '15'),
  (1152, 'math', 'algebra', '2x - 1 = 21', '11'),
  (1153, 'math', 'algebra', '2x + 3 = 7', '2'),
  (1154, 'math', 'algebra', '2x + 1 = 17', '8'),
  (1155, 'math', 'algebra', '2x + 1 = 19', '9'),
  (1156, 'math', 'algebra', 'x / 2 = 7', '14'),
  (1157, 'math', 'algebra', '2(x - 1) = 14', '8'),
  (1158, 'math', 'algebra', '2x + 3 = 5', '1'),
  (1159, 'math', 'algebra', '2(x + 2) = 16', '6'),
  (1160, 'math', 'algebra', '2x + 3 = 13', '5'),
  (1161, 'math', 'algebra', '2x + 4 = 10', '3'),
  (1162, 'math', 'algebra', '2x - 1 = 25', '13'),
  (1163, 'math', 'algebra', '2x - 1 = 35', '18'),
  (1164, 'math', 'algebra', '2x - 2 = 12', '7'),
  (1165, 'math', 'algebra', '2x + 1 = 15', '7'),
  (1166, 'math', 'algebra', '2x + 3 = 17', '7'),
  (1167, 'math', 'algebra', '2(x - 2) = 10', '7'),
  (1168, 'math', 'algebra', '2x + 6 = 12', '3'),
  (1169, 'math', 'algebra', '2x + 5 = 9', '2'),
  (1170, 'math', 'algebra', 'x / 3 = 10', '30'),
  (1171, 'math', 'algebra', '2x + 3 = 35', '16'),
  (1172, 'math', 'algebra', '2x + 6 = 10', '2'),
  (1173, 'math', 'algebra', '2x + 6 = 18', '6'),
  (1174, 'math', 'algebra', '3x + 2 = 1x + 4', '1'),
  (1175, 'math', 'algebra', '2(x + 1) = 40', '19'),
  (1176, 'math', 'algebra', '2x - 4 = 24', '14'),
  (1177, 'math', 'algebra', '2x + 5 = 27', '11'),
  (1178, 'math', 'algebra', '2x + 3 = 27', '12'),
  (1179, 'math', 'algebra', '2x - 4 = 34', '19'),
  (1180, 'math', 'algebra', '3x + 1 = 1x + 3', '1'),
  (1181, 'math', 'algebra', '2x + 1 = 37', '18'),
  (1182, 'math', 'algebra', 'x / 2 = 15', '30'),
  (1183, 'math', 'algebra', 'x / 2 = 17', '34'),
  (1184, 'math', 'algebra', '2x - 4 = 26', '15'),
  (1185, 'math', 'algebra', '2x + 6 = 36', '15'),
  (1186, 'math', 'algebra', '2x + 5 = 11', '3'),
  (1187, 'math', 'algebra', '2x + 6 = 8', '1'),
  (1188, 'math', 'algebra', 'x / 3 = 7', '21'),
  (1189, 'math', 'algebra', '2x + 1 = 25', '12'),
  (1190, 'math', 'algebra', '2x - 5 = 13', '9'),
  (1191, 'math', 'algebra', 'x / 3 = 15', '45'),
  (1192, 'math', 'algebra', 'x / 3 = 18', '54'),
  (1193, 'math', 'algebra', '3x + 7 = 1x + 9', '1'),
  (1194, 'math', 'algebra', '2(x + 2) = 28', '12'),
  (1195, 'math', 'algebra', '2x + 1 = 29', '14'),
  (1196, 'math', 'algebra', '2x + 1 = 33', '16'),
  (1197, 'math', 'algebra', 'x / 3 = 13', '39'),
  (1198, 'math', 'algebra', '3x + 8 = 1x + 10', '1'),
  (1199, 'math', 'algebra', '2(x + 2) = 32', '14'),
  (1200, 'math', 'algebra', 'x / 2 = 16', '32'),
  (1201, 'math', 'algebra', 'x / 3 = 17', '51'),
  (1202, 'math', 'algebra', '2x + 5 = 19', '7'),
  (1203, 'math', 'algebra', '2x + 4 = 34', '15'),
  (1204, 'math', 'algebra', '3x + 4 = 1x + 6', '1'),
  (1205, 'math', 'algebra', '3x + 12 = 1x + 16', '2'),
  (1206, 'math', 'algebra', '2x + 5 = 15', '5'),
  (1207, 'math', 'algebra', '2x - 4 = 16', '10'),
  (1208, 'math', 'algebra', '2x + 4 = 36', '16'),
  (1209, 'math', 'algebra', '2x - 4 = 32', '18'),
  (1210, 'math', 'algebra', '2(x + 3) = 8', '1'),
  (1211, 'math', 'algebra', '2x - 4 = 30', '17'),
  (1212, 'math', 'algebra', '2x + 5 = 35', '15'),
  (1213, 'math', 'algebra', '2x + 4 = 30', '13'),
  (1214, 'math', 'algebra', '2x - 5 = 9', '7'),
  (1215, 'math', 'algebra', '2x + 5 = 39', '17'),
  (1216, 'math', 'algebra', 'x / 3 = 14', '42'),
  (1217, 'math', 'algebra', '2(x + 2) = 36', '16'),
  (1218, 'math', 'algebra', '2x - 4 = 14', '9'),
  (1219, 'math', 'algebra', '2x + 2 = 36', '17'),
  (1220, 'math', 'algebra', '2x + 1 = 31', '15'),
  (1221, 'math', 'algebra', '2x - 5 = 33', '19'),
  (1222, 'math', 'algebra', '2x - 5 = 25', '15'),
  (1223, 'math', 'algebra', '2x + 6 = 40', '17'),
  (1224, 'math', 'algebra', 'x / 2 = 18', '36'),
  (1225, 'math', 'algebra', '2x - 4 = 2', '3'),
  (1226, 'math', 'algebra', '2x + 4 = 38', '17'),
  (1227, 'math', 'algebra', '2x + 1 = 27', '13'),
  (1228, 'math', 'algebra', '2(x + 1) = 32', '15'),
  (1229, 'math', 'algebra', '2x + 5 = 29', '12'),
  (1230, 'math', 'algebra', '3x + 14 = 1x + 16', '1'),
  (1231, 'math', 'algebra', '2x + 5 = 43', '19'),
  (1232, 'math', 'algebra', '3x + 3 = 1x + 5', '1'),
  (1233, 'math', 'algebra', '2x - 5 = 17', '11'),
  (1234, 'math', 'algebra', '2x + 5 = 23', '9'),
  (1235, 'math', 'algebra', 'x / 3 = 19', '57'),
  (1236, 'math', 'algebra', 'x / 4 = 2', '8'),
  (1237, 'math', 'algebra', '2x + 6 = 28', '11'),
  (1238, 'math', 'algebra', '3x + 12 = 1x + 14', '1'),
  (1239, 'math', 'algebra', '2(x + 2) = 34', '15'),
  (1240, 'math', 'algebra', 'x / 4 = 3', '12'),
  (1241, 'math', 'algebra', 'x / 3 = 8', '24'),
  (1242, 'math', 'algebra', '3x + 14 = 1x + 18', '2'),
  (1243, 'math', 'algebra', '2x - 5 = 23', '14'),
  (1244, 'math', 'algebra', '2x + 5 = 33', '14'),
  (1245, 'math', 'algebra', '2x - 5 = 1', '3'),
  (1246, 'math', 'algebra', 'x / 3 = 11', '33'),
  (1247, 'math', 'algebra', '2x - 5 = 29', '17'),
  (1248, 'math', 'algebra', '2x - 4 = 6', '5'),
  (1249, 'math', 'algebra', 'x / 4 = 4', '16'),
  (1250, 'math', 'algebra', '2x + 1 = 35', '17'),
  (1251, 'math', 'algebra', '2x - 5 = 5', '5'),
  (1252, 'math', 'algebra', '2x + 6 = 32', '13'),
  (1253, 'math', 'algebra', '2x + 3 = 33', '15'),
  (1254, 'math', 'algebra', '2x - 5 = 21', '13'),
  (1255, 'math', 'algebra', '2x + 3 = 37', '17'),
  (1256, 'math', 'algebra', '2x + 6 = 14', '4'),
  (1257, 'math', 'algebra', '2x + 6 = 38', '16'),
  (1258, 'math', 'algebra', '3x + 9 = 1x + 13', '2'),
  (1259, 'math', 'algebra', '2(x + 1) = 34', '16'),
  (1260, 'math', 'algebra', '2x - 4 = 18', '11'),
  (1261, 'math', 'algebra', '3x + 9 = 1x + 11', '1'),
  (1262, 'math', 'algebra', '3x + 4 = 1x + 8', '2'),
  (1263, 'math', 'algebra', '2(x + 2) = 30', '13'),
  (1264, 'math', 'algebra', '2x + 5 = 31', '13'),
  (1265, 'math', 'algebra', 'x / 3 = 16', '48'),
  (1266, 'math', 'algebra', '2x + 6 = 42', '18'),
  (1267, 'math', 'algebra', '3x + 8 = 1x + 12', '2'),
  (1268, 'math', 'algebra', '2x - 4 = 10', '7'),
  (1269, 'math', 'algebra', '2x + 2 = 30', '14'),
  (1270, 'math', 'algebra', '3x + 10 = 1x + 12', '1'),
  (1271, 'math', 'algebra', 'x / 3 = 12', '36'),
  (1272, 'math', 'algebra', '2x - 5 = 7', '6'),
  (1273, 'math', 'algebra', '3x + 10 = 1x + 14', '2'),
  (1274, 'math', 'algebra', '3x + 2 = 1x + 6', '2'),
  (1275, 'math', 'algebra', '3x + 5 = 1x + 9', '2'),
  (1276, 'math', 'algebra', '2(x + 2) = 42', '19'),
  (1277, 'math', 'algebra', '3x + 6 = 1x + 8', '1'),
  (1278, 'math', 'algebra', '2x + 6 = 24', '9'),
  (1279, 'math', 'algebra', '3x + 11 = 1x + 13', '1'),
  (1280, 'math', 'algebra', '2x + 6 = 26', '10'),
  (1281, 'math', 'algebra', '2x + 5 = 25', '10'),
  (1282, 'math', 'algebra', '2x - 5 = 27', '16'),
  (1283, 'math', 'algebra', '2(x + 1) = 36', '17'),
  (1284, 'math', 'algebra', '2x + 6 = 44', '19'),
  (1285, 'math', 'algebra', '2x - 5 = 3', '4'),
  (1286, 'math', 'algebra', '2x + 6 = 34', '14'),
  (1287, 'math', 'algebra', '2(x + 1) = 38', '18'),
  (1288, 'math', 'algebra', '2x - 4 = 22', '13'),
  (1289, 'math', 'algebra', '2x + 1 = 39', '19'),
  (1290, 'math', 'algebra', '2x - 4 = 8', '6'),
  (1291, 'math', 'algebra', '2x + 2 = 26', '12'),
  (1292, 'math', 'algebra', '2x - 5 = 11', '8'),
  (1293, 'math', 'algebra', '2x - 4 = 4', '4'),
  (1294, 'math', 'algebra', '3x + 1 = 1x + 5', '2'),
  (1295, 'math', 'algebra', '2x - 5 = 19', '12'),
  (1296, 'math', 'algebra', '2x + 5 = 41', '18'),
  (1297, 'math', 'algebra', '2x + 4 = 32', '14'),
  (1298, 'math', 'algebra', '2x + 5 = 37', '16'),
  (1299, 'math', 'algebra', '2x - 4 = 20', '12'),
  (1300, 'math', 'algebra', '2x + 4 = 40', '18'),
  (1301, 'math', 'algebra', '2x + 5 = 17', '6'),
  (1302, 'math', 'algebra', '3x + 13 = 1x + 17', '2'),
  (1303, 'math', 'algebra', '2x - 4 = 12', '8'),
  (1304, 'math', 'algebra', '2x + 5 = 13', '4'),
  (1305, 'math', 'algebra', '2x + 2 = 32', '15'),
  (1306, 'math', 'algebra', '2x + 6 = 20', '7'),
  (1307, 'math', 'algebra', '2(x + 2) = 38', '17'),
  (1308, 'math', 'algebra', '2(x + 2) = 40', '18'),
  (1309, 'math', 'algebra', '3x + 7 = 1x + 11', '2'),
  (1310, 'math', 'algebra', '2x + 6 = 22', '8'),
  (1311, 'math', 'algebra', '2x + 4 = 42', '19'),
  (1312, 'math', 'algebra', '3x + 6 = 1x + 10', '2'),
  (1313, 'math', 'algebra', '2x + 2 = 40', '19'),
  (1314, 'math', 'algebra', 'x / 3 = 6', '18'),
  (1315, 'math', 'algebra', '3x + 3 = 1x + 7', '2'),
  (1316, 'math', 'algebra', '2x + 3 = 41', '19'),
  (1317, 'math', 'algebra', '2x + 6 = 30', '12'),
  (1318, 'math', 'algebra', '2x + 3 = 29', '13'),
  (1319, 'math', 'algebra', 'x / 2 = 19', '38'),
  (1320, 'math', 'algebra', 'x / 3 = 9', '27'),
  (1321, 'math', 'algebra', '2x + 3 = 39', '18'),
  (1322, 'math', 'algebra', '2x + 2 = 28', '13'),
  (1323, 'math', 'algebra', '2x + 6 = 16', '5'),
  (1324, 'math', 'algebra', '3x + 5 = 1x + 7', '1'),
  (1325, 'math', 'algebra', '2x + 2 = 38', '18'),
  (1326, 'math', 'algebra', '3x + 11 = 1x + 15', '2'),
  (1327, 'math', 'algebra', '2x - 5 = 15', '10'),
  (1328, 'math', 'algebra', '2x + 4 = 28', '12'),
  (1329, 'math', 'algebra', '3x + 13 = 1x + 15', '1'),
  (1330, 'math', 'algebra', '2x + 3 = 31', '14'),
  (1331, 'math', 'algebra', '2x + 2 = 34', '16'),
  (1332, 'math', 'algebra', '2x - 5 = 31', '18'),
  (1333, 'math', 'algebra', '2x + 5 = 21', '8'),
  (1334, 'math', 'algebra', '2x - 4 = 28', '16')
on conflict (id) do update set
  subject = excluded.subject,
  category = excluded.category,
  prompt = excluded.prompt,
  answer = excluded.answer;

-- ============================================================
-- English · Grammar (334 questions)
-- ============================================================
insert into public.quiz_questions (id, subject, category, prompt, answer) values
  (2001, 'english', 'grammar', 'We have took the bus.', 'We have taken the bus.'),
  (2002, 'english', 'grammar', 'Their going to the park.', 'They''re going to the park.'),
  (2003, 'english', 'grammar', 'The car don''t like the plan.', 'The car doesn''t like the plan.'),
  (2004, 'english', 'grammar', 'She have went to the store.', 'She has gone to the store.'),
  (2005, 'english', 'grammar', 'The engineer have a great idea.', 'The engineer has a great idea.'),
  (2006, 'english', 'grammar', 'The dog run every morning.', 'The dog runs every morning.'),
  (2007, 'english', 'grammar', 'The teachers runs fast.', 'The teachers run fast.'),
  (2008, 'english', 'grammar', 'The journalists knows the answer.', 'The journalists know the answer.'),
  (2009, 'english', 'grammar', 'The painters likes the new plan.', 'The painters like the new plan.'),
  (2010, 'english', 'grammar', 'She won''t go nowhere.', 'She won''t go anywhere.'),
  (2011, 'english', 'grammar', 'The plumbers wants to help.', 'The plumbers want to help.'),
  (2012, 'english', 'grammar', 'The chefs runs fast.', 'The chefs run fast.'),
  (2013, 'english', 'grammar', 'She singed a beautiful song.', 'She sang a beautiful song.'),
  (2014, 'english', 'grammar', 'The managers runs fast.', 'The managers run fast.'),
  (2015, 'english', 'grammar', 'I have swam in that lake.', 'I have swum in that lake.'),
  (2016, 'english', 'grammar', 'The birds runs fast.', 'The birds run fast.'),
  (2017, 'english', 'grammar', 'Who''s book is this?', 'Whose book is this?'),
  (2018, 'english', 'grammar', 'The photographers wants to help.', 'The photographers want to help.'),
  (2019, 'english', 'grammar', 'Our neighbor have a great idea.', 'Our neighbor has a great idea.'),
  (2020, 'english', 'grammar', 'She didn''t say nothing.', 'She didn''t say anything.'),
  (2021, 'english', 'grammar', 'Your going to love this movie.', 'You''re going to love this movie.'),
  (2022, 'english', 'grammar', 'Me and her like the same music.', 'She and I like the same music.'),
  (2023, 'english', 'grammar', 'She were the first to arrive.', 'She was the first to arrive.'),
  (2024, 'english', 'grammar', 'It was the most worst day ever.', 'It was the worst day ever.'),
  (2025, 'english', 'grammar', 'The coaches wants to help.', 'The coaches want to help.'),
  (2026, 'english', 'grammar', 'The student run every morning.', 'The student runs every morning.'),
  (2027, 'english', 'grammar', 'The managers likes the new plan.', 'The managers like the new plan.'),
  (2028, 'english', 'grammar', 'We was at the park yesterday.', 'We were at the park yesterday.'),
  (2029, 'english', 'grammar', 'There house is on the corner.', 'Their house is on the corner.'),
  (2030, 'english', 'grammar', 'Their coming over for dinner.', 'They''re coming over for dinner.'),
  (2031, 'english', 'grammar', 'They have broke the vase.', 'They have broken the vase.'),
  (2032, 'english', 'grammar', 'The pilot want to help.', 'The pilot wants to help.'),
  (2033, 'english', 'grammar', 'He throwed the ball far.', 'He threw the ball far.'),
  (2034, 'english', 'grammar', 'She catched the ball.', 'She caught the ball.'),
  (2035, 'english', 'grammar', 'The manager don''t like cold weather.', 'The manager doesn''t like cold weather.'),
  (2036, 'english', 'grammar', 'The cars runs fast.', 'The cars run fast.'),
  (2037, 'english', 'grammar', 'The teacher run every morning.', 'The teacher runs every morning.'),
  (2038, 'english', 'grammar', 'This is the most easiest test.', 'This is the easiest test.'),
  (2039, 'english', 'grammar', 'The kids was playing outside.', 'The kids were playing outside.'),
  (2040, 'english', 'grammar', 'She has wrote three letters.', 'She has written three letters.'),
  (2041, 'english', 'grammar', 'Our neighbors runs fast.', 'Our neighbors run fast.'),
  (2042, 'english', 'grammar', 'They discussed about the plan.', 'They discussed the plan.'),
  (2043, 'english', 'grammar', 'The students runs fast.', 'The students run fast.'),
  (2044, 'english', 'grammar', 'The farmers runs fast.', 'The farmers run fast.'),
  (2045, 'english', 'grammar', 'Me and him went to the store.', 'He and I went to the store.'),
  (2046, 'english', 'grammar', 'The gardeners knows the answer.', 'The gardeners know the answer.'),
  (2047, 'english', 'grammar', 'They''re car is parked outside.', 'Their car is parked outside.'),
  (2048, 'english', 'grammar', 'I knowed the answer.', 'I knew the answer.'),
  (2049, 'english', 'grammar', 'He apologized for his mistake to me.', 'He apologized to me for his mistake.'),
  (2050, 'english', 'grammar', 'The plumber want to help.', 'The plumber wants to help.'),
  (2051, 'english', 'grammar', 'The lawyer want to help.', 'The lawyer wants to help.'),
  (2052, 'english', 'grammar', 'The painter have a great idea.', 'The painter has a great idea.'),
  (2053, 'english', 'grammar', 'The pilots wants to help.', 'The pilots want to help.'),
  (2054, 'english', 'grammar', 'The farmer run every morning.', 'The farmer runs every morning.'),
  (2055, 'english', 'grammar', 'My sister don''t like the project.', 'My sister doesn''t like the project.'),
  (2056, 'english', 'grammar', 'The doctor run every morning.', 'The doctor runs every morning.'),
  (2057, 'english', 'grammar', 'He done his homework already.', 'He did his homework already.'),
  (2058, 'english', 'grammar', 'The waiters knows the answer.', 'The waiters know the answer.'),
  (2059, 'english', 'grammar', 'She drawed a picture.', 'She drew a picture.'),
  (2060, 'english', 'grammar', 'The musicians knows the answer.', 'The musicians know the answer.'),
  (2061, 'english', 'grammar', 'I depend of my parents for advice.', 'I depend on my parents for advice.'),
  (2062, 'english', 'grammar', 'The books was on the table.', 'The books were on the table.'),
  (2063, 'english', 'grammar', 'This road is more curvier than the other.', 'This road is curvier than the other.'),
  (2064, 'english', 'grammar', 'There going to the park.', 'They''re going to the park.'),
  (2065, 'english', 'grammar', 'She is more taller than him.', 'She is taller than him.'),
  (2066, 'english', 'grammar', 'The pilot know the answer.', 'The pilot knows the answer.'),
  (2067, 'english', 'grammar', 'I saw a elephant at the zoo.', 'I saw an elephant at the zoo.'),
  (2068, 'english', 'grammar', 'The doctor don''t like spicy food.', 'The doctor doesn''t like spicy food.'),
  (2069, 'english', 'grammar', 'The drivers likes the new plan.', 'The drivers like the new plan.'),
  (2070, 'english', 'grammar', 'He were confused by the question.', 'He was confused by the question.'),
  (2071, 'english', 'grammar', 'The lawyers wants to help.', 'The lawyers want to help.'),
  (2072, 'english', 'grammar', 'The journalist want to help.', 'The journalist wants to help.'),
  (2073, 'english', 'grammar', 'The chefs likes the new plan.', 'The chefs like the new plan.'),
  (2074, 'english', 'grammar', 'We have chose the winner.', 'We have chosen the winner.'),
  (2075, 'english', 'grammar', 'The librarian want to help.', 'The librarian wants to help.'),
  (2076, 'english', 'grammar', 'They was not listening.', 'They were not listening.'),
  (2077, 'english', 'grammar', 'The dogs runs fast.', 'The dogs run fast.'),
  (2078, 'english', 'grammar', 'I seen the movie last night.', 'I saw the movie last night.'),
  (2079, 'english', 'grammar', 'He didn''t do nothing wrong.', 'He didn''t do anything wrong.'),
  (2080, 'english', 'grammar', 'The players was excited.', 'The players were excited.'),
  (2081, 'english', 'grammar', 'She is good in math.', 'She is good at math.'),
  (2082, 'english', 'grammar', 'He has spoke to the manager.', 'He has spoken to the manager.'),
  (2083, 'english', 'grammar', 'The child run every morning.', 'The child runs every morning.'),
  (2084, 'english', 'grammar', 'He is the most tallest boy.', 'He is the tallest boy.'),
  (2085, 'english', 'grammar', 'The doctor have a great idea.', 'The doctor has a great idea.'),
  (2086, 'english', 'grammar', 'I don''t have no money.', 'I don''t have any money.'),
  (2087, 'english', 'grammar', 'The nurse know the answer.', 'The nurse knows the answer.'),
  (2088, 'english', 'grammar', 'She is afraid from spiders.', 'She is afraid of spiders.'),
  (2089, 'english', 'grammar', 'Your the best friend I have.', 'You''re the best friend I have.'),
  (2090, 'english', 'grammar', 'The company run every morning.', 'The company runs every morning.'),
  (2091, 'english', 'grammar', 'The librarian know the answer.', 'The librarian knows the answer.'),
  (2092, 'english', 'grammar', 'I have a umbrella with me.', 'I have an umbrella with me.'),
  (2093, 'english', 'grammar', 'This book is more better than that one.', 'This book is better than that one.'),
  (2094, 'english', 'grammar', 'The dog don''t like rainy days.', 'The dog doesn''t like rainy days.'),
  (2095, 'english', 'grammar', 'I am agree with you.', 'I agree with you.'),
  (2096, 'english', 'grammar', 'The nurse want to help.', 'The nurse wants to help.'),
  (2097, 'english', 'grammar', 'The bird don''t like the plan.', 'The bird doesn''t like the plan.'),
  (2098, 'english', 'grammar', 'The gardener want to help.', 'The gardener wants to help.'),
  (2099, 'english', 'grammar', 'She sings more beautifuller than me.', 'She sings more beautifully than me.'),
  (2100, 'english', 'grammar', 'The farmers likes the new plan.', 'The farmers like the new plan.'),
  (2101, 'english', 'grammar', 'The architects wants to help.', 'The architects want to help.'),
  (2102, 'english', 'grammar', 'The engineers runs fast.', 'The engineers run fast.'),
  (2103, 'english', 'grammar', 'The journalists wants to help.', 'The journalists want to help.'),
  (2104, 'english', 'grammar', 'The photographers knows the answer.', 'The photographers know the answer.'),
  (2105, 'english', 'grammar', 'I have ran five miles.', 'I have run five miles.'),
  (2106, 'english', 'grammar', 'The farmer don''t like the new rules.', 'The farmer doesn''t like the new rules.'),
  (2107, 'english', 'grammar', 'The musician know the answer.', 'The musician knows the answer.'),
  (2108, 'english', 'grammar', 'We was happy.', 'We were happy.'),
  (2109, 'english', 'grammar', 'They have ate dinner already.', 'They have eaten dinner already.'),
  (2110, 'english', 'grammar', 'The student don''t like early mornings.', 'The student doesn''t like early mornings.'),
  (2111, 'english', 'grammar', 'The artist don''t like the plan.', 'The artist doesn''t like the plan.'),
  (2112, 'english', 'grammar', 'I were tired.', 'I was tired.'),
  (2113, 'english', 'grammar', 'I ain''t got no time.', 'I don''t have any time.'),
  (2114, 'english', 'grammar', 'Me and my friend went shopping.', 'My friend and I went shopping.'),
  (2115, 'english', 'grammar', 'He is capable to do it.', 'He is capable of doing it.'),
  (2116, 'english', 'grammar', 'The waiter know the answer.', 'The waiter knows the answer.'),
  (2117, 'english', 'grammar', 'The child don''t like long meetings.', 'The child doesn''t like long meetings.'),
  (2118, 'english', 'grammar', 'The dog wagged it''s tail.', 'The dog wagged its tail.'),
  (2119, 'english', 'grammar', 'The car run every morning.', 'The car runs every morning.'),
  (2120, 'english', 'grammar', 'The children likes the new plan.', 'The children like the new plan.'),
  (2121, 'english', 'grammar', 'The bird run every morning.', 'The bird runs every morning.'),
  (2122, 'english', 'grammar', 'The baby have a great idea.', 'The baby has a great idea.'),
  (2123, 'english', 'grammar', 'The plumber know the answer.', 'The plumber knows the answer.'),
  (2124, 'english', 'grammar', 'The gardener know the answer.', 'The gardener knows the answer.'),
  (2125, 'english', 'grammar', 'The architects knows the answer.', 'The architects know the answer.'),
  (2126, 'english', 'grammar', 'They was ready.', 'They were ready.'),
  (2127, 'english', 'grammar', 'The architect want to help.', 'The architect wants to help.'),
  (2128, 'english', 'grammar', 'The doctors runs fast.', 'The doctors run fast.'),
  (2129, 'english', 'grammar', 'The coaches knows the answer.', 'The coaches know the answer.'),
  (2130, 'english', 'grammar', 'My brother have a great idea.', 'My brother has a great idea.'),
  (2131, 'english', 'grammar', 'The pilots knows the answer.', 'The pilots know the answer.'),
  (2132, 'english', 'grammar', 'We didn''t see nobody.', 'We didn''t see anybody.'),
  (2133, 'english', 'grammar', 'The coach know the answer.', 'The coach knows the answer.'),
  (2134, 'english', 'grammar', 'The driver have a great idea.', 'The driver has a great idea.'),
  (2135, 'english', 'grammar', 'The engineer don''t like the new rules.', 'The engineer doesn''t like the new rules.'),
  (2136, 'english', 'grammar', 'Its a beautiful day.', 'It''s a beautiful day.'),
  (2137, 'english', 'grammar', 'I can''t hardly wait.', 'I can hardly wait.'),
  (2138, 'english', 'grammar', 'The musician want to help.', 'The musician wants to help.'),
  (2139, 'english', 'grammar', 'He teached the class yesterday.', 'He taught the class yesterday.'),
  (2140, 'english', 'grammar', 'Its raining outside.', 'It''s raining outside.'),
  (2141, 'english', 'grammar', 'The lawyers knows the answer.', 'The lawyers know the answer.'),
  (2142, 'english', 'grammar', 'The chef have a great idea.', 'The chef has a great idea.'),
  (2143, 'english', 'grammar', 'The children runs fast.', 'The children run fast.'),
  (2144, 'english', 'grammar', 'They don''t never come on time.', 'They never come on time.'),
  (2145, 'english', 'grammar', 'She is interested on painting.', 'She is interested in painting.'),
  (2146, 'english', 'grammar', 'The artists likes the new plan.', 'The artists like the new plan.'),
  (2147, 'english', 'grammar', 'The nurses wants to help.', 'The nurses want to help.'),
  (2148, 'english', 'grammar', 'We arrived to the airport early.', 'We arrived at the airport early.'),
  (2149, 'english', 'grammar', 'Our neighbor run every morning.', 'Our neighbor runs every morning.'),
  (2150, 'english', 'grammar', 'The coach want to help.', 'The coach wants to help.'),
  (2151, 'english', 'grammar', 'The photographer want to help.', 'The photographer wants to help.'),
  (2152, 'english', 'grammar', 'The waiters wants to help.', 'The waiters want to help.'),
  (2153, 'english', 'grammar', 'You was late.', 'You were late.'),
  (2154, 'english', 'grammar', 'The doctors likes the new plan.', 'The doctors like the new plan.'),
  (2155, 'english', 'grammar', 'He runs more faster than his brother.', 'He runs faster than his brother.'),
  (2156, 'english', 'grammar', 'The photographer know the answer.', 'The photographer knows the answer.'),
  (2157, 'english', 'grammar', 'We had went there before.', 'We had gone there before.'),
  (2158, 'english', 'grammar', 'The company don''t like loud music.', 'The company doesn''t like loud music.'),
  (2159, 'english', 'grammar', 'The musicians wants to help.', 'The musicians want to help.'),
  (2160, 'english', 'grammar', 'The journalist know the answer.', 'The journalist knows the answer.'),
  (2161, 'english', 'grammar', 'The student have a great idea.', 'The student has a great idea.'),
  (2162, 'english', 'grammar', 'The child have a great idea.', 'The child has a great idea.'),
  (2163, 'english', 'grammar', 'The teacher don''t like the project.', 'The teacher doesn''t like the project.'),
  (2164, 'english', 'grammar', 'Our neighbors likes the new plan.', 'Our neighbors like the new plan.'),
  (2165, 'english', 'grammar', 'The architect know the answer.', 'The architect knows the answer.'),
  (2166, 'english', 'grammar', 'The birds likes the new plan.', 'The birds like the new plan.'),
  (2167, 'english', 'grammar', 'Her and I share a room.', 'She and I share a room.'),
  (2168, 'english', 'grammar', 'The athlete have finished the task.', 'The athlete has finished the task.'),
  (2169, 'english', 'grammar', 'Our friends doesn''t enjoy the noise.', 'Our friends don''t enjoy the noise.'),
  (2170, 'english', 'grammar', 'The sculptor don''t enjoy loud parties.', 'The sculptor doesn''t enjoy loud parties.'),
  (2171, 'english', 'grammar', 'The historian have finished the task.', 'The historian has finished the task.'),
  (2172, 'english', 'grammar', 'Our friend go to work every day.', 'Our friend goes to work every day.'),
  (2173, 'english', 'grammar', 'She has went home already.', 'She has gone home already.'),
  (2174, 'english', 'grammar', 'Each of the students are responsible.', 'Each of the students is responsible.'),
  (2175, 'english', 'grammar', 'The mayor have finished the task.', 'The mayor has finished the task.'),
  (2176, 'english', 'grammar', 'Neither of the answers are correct.', 'Neither of the answers is correct.'),
  (2177, 'english', 'grammar', 'The baristas doesn''t enjoy the noise.', 'The baristas don''t enjoy the noise.'),
  (2178, 'english', 'grammar', 'They''re bags are packed.', 'Their bags are packed.'),
  (2179, 'english', 'grammar', 'She can''t never remember his name.', 'She can never remember his name.'),
  (2180, 'english', 'grammar', 'The professors goes to work every day.', 'The professors go to work every day.'),
  (2181, 'english', 'grammar', 'The puppy don''t enjoy bright colors.', 'The puppy doesn''t enjoy bright colors.'),
  (2182, 'english', 'grammar', 'The technician have finished the task.', 'The technician has finished the task.'),
  (2183, 'english', 'grammar', 'The captains doesn''t enjoy the noise.', 'The captains don''t enjoy the noise.'),
  (2184, 'english', 'grammar', 'The historians has finished the task.', 'The historians have finished the task.'),
  (2185, 'english', 'grammar', 'The puppies doesn''t enjoy the noise.', 'The puppies don''t enjoy the noise.'),
  (2186, 'english', 'grammar', 'She has flew to Paris twice.', 'She has flown to Paris twice.'),
  (2187, 'english', 'grammar', 'The director have finished the task.', 'The director has finished the task.'),
  (2188, 'english', 'grammar', 'He has ate all the food.', 'He has eaten all the food.'),
  (2189, 'english', 'grammar', 'The cat go to work every day.', 'The cat goes to work every day.'),
  (2190, 'english', 'grammar', 'The surgeons has finished the task.', 'The surgeons have finished the task.'),
  (2191, 'english', 'grammar', 'The vets doesn''t enjoy the noise.', 'The vets don''t enjoy the noise.'),
  (2192, 'english', 'grammar', 'There is many reasons to celebrate.', 'There are many reasons to celebrate.'),
  (2193, 'english', 'grammar', 'I have began the report.', 'I have begun the report.'),
  (2194, 'english', 'grammar', 'Here is the results of the test.', 'Here are the results of the test.'),
  (2195, 'english', 'grammar', 'The surgeon have finished the task.', 'The surgeon has finished the task.'),
  (2196, 'english', 'grammar', 'Our friends goes to work every day.', 'Our friends go to work every day.'),
  (2197, 'english', 'grammar', 'The director don''t enjoy late nights.', 'The director doesn''t enjoy late nights.'),
  (2198, 'english', 'grammar', 'She has drove here alone.', 'She has driven here alone.'),
  (2199, 'english', 'grammar', 'They have rode the train before.', 'They have ridden the train before.'),
  (2200, 'english', 'grammar', 'The director go to work every day.', 'The director goes to work every day.'),
  (2201, 'english', 'grammar', 'We couldn''t hardly see the road.', 'We could hardly see the road.'),
  (2202, 'english', 'grammar', 'The puppy go to work every day.', 'The puppy goes to work every day.'),
  (2203, 'english', 'grammar', 'The sculptor have finished the task.', 'The sculptor has finished the task.'),
  (2204, 'english', 'grammar', 'Its been a long day.', 'It''s been a long day.'),
  (2205, 'english', 'grammar', 'The toddler go to work every day.', 'The toddler goes to work every day.'),
  (2206, 'english', 'grammar', 'The toddler don''t enjoy the final exam.', 'The toddler doesn''t enjoy the final exam.'),
  (2207, 'english', 'grammar', 'There going to move to a new city.', 'They''re going to move to a new city.'),
  (2208, 'english', 'grammar', 'He has forgot his keys again.', 'He has forgotten his keys again.'),
  (2209, 'english', 'grammar', 'The team played good.', 'The team played well.'),
  (2210, 'english', 'grammar', 'The vets has finished the task.', 'The vets have finished the task.'),
  (2211, 'english', 'grammar', 'The vets goes to work every day.', 'The vets go to work every day.'),
  (2212, 'english', 'grammar', 'The barista have finished the task.', 'The barista has finished the task.'),
  (2213, 'english', 'grammar', 'The puppies has finished the task.', 'The puppies have finished the task.'),
  (2214, 'english', 'grammar', 'The sculptor go to work every day.', 'The sculptor goes to work every day.'),
  (2215, 'english', 'grammar', 'The buses goes to work every day.', 'The buses go to work every day.'),
  (2216, 'english', 'grammar', 'The inventors doesn''t enjoy the noise.', 'The inventors don''t enjoy the noise.'),
  (2217, 'english', 'grammar', 'Our friends has finished the task.', 'Our friends have finished the task.'),
  (2218, 'english', 'grammar', 'The organization don''t enjoy loud parties.', 'The organization doesn''t enjoy loud parties.'),
  (2219, 'english', 'grammar', 'The organization go to work every day.', 'The organization goes to work every day.'),
  (2220, 'english', 'grammar', 'The toddlers doesn''t enjoy the noise.', 'The toddlers don''t enjoy the noise.'),
  (2221, 'english', 'grammar', 'The instructions is clear.', 'The instructions are clear.'),
  (2222, 'english', 'grammar', 'He answered the question quick.', 'He answered the question quickly.'),
  (2223, 'english', 'grammar', 'The news are surprising today.', 'The news is surprising today.'),
  (2224, 'english', 'grammar', 'The surgeons doesn''t enjoy the noise.', 'The surgeons don''t enjoy the noise.'),
  (2225, 'english', 'grammar', 'The inventors has finished the task.', 'The inventors have finished the task.'),
  (2226, 'english', 'grammar', 'The fish doesn''t enjoy the noise.', 'The fish don''t enjoy the noise.'),
  (2227, 'english', 'grammar', 'The scissors is on the desk.', 'The scissors are on the desk.'),
  (2228, 'english', 'grammar', 'There the ones who called us.', 'They''re the ones who called us.'),
  (2229, 'english', 'grammar', 'The sculptors goes to work every day.', 'The sculptors go to work every day.'),
  (2230, 'english', 'grammar', 'My uncle have finished the task.', 'My uncle has finished the task.'),
  (2231, 'english', 'grammar', 'My cousins doesn''t enjoy the noise.', 'My cousins don''t enjoy the noise.'),
  (2232, 'english', 'grammar', 'I haven''t got no idea.', 'I haven''t got any idea.'),
  (2233, 'english', 'grammar', 'The captains has finished the task.', 'The captains have finished the task.'),
  (2234, 'english', 'grammar', 'The novelist don''t enjoy the new policy.', 'The novelist doesn''t enjoy the new policy.'),
  (2235, 'english', 'grammar', 'The technician go to work every day.', 'The technician goes to work every day.'),
  (2236, 'english', 'grammar', 'The professor don''t enjoy the morning routine.', 'The professor doesn''t enjoy the morning routine.'),
  (2237, 'english', 'grammar', 'My cousin don''t enjoy the morning routine.', 'My cousin doesn''t enjoy the morning routine.'),
  (2238, 'english', 'grammar', 'The baristas has finished the task.', 'The baristas have finished the task.'),
  (2239, 'english', 'grammar', 'The inventor have finished the task.', 'The inventor has finished the task.'),
  (2240, 'english', 'grammar', 'The captain have finished the task.', 'The captain has finished the task.'),
  (2241, 'english', 'grammar', 'The athlete go to work every day.', 'The athlete goes to work every day.'),
  (2242, 'english', 'grammar', 'The professor go to work every day.', 'The professor goes to work every day.'),
  (2243, 'english', 'grammar', 'The pilot go to work every day.', 'The pilot goes to work every day.'),
  (2244, 'english', 'grammar', 'We have did our best.', 'We have done our best.'),
  (2245, 'english', 'grammar', 'The pilots has finished the task.', 'The pilots have finished the task.'),
  (2246, 'english', 'grammar', 'The cats has finished the task.', 'The cats have finished the task.'),
  (2247, 'english', 'grammar', 'The historian don''t enjoy long drives.', 'The historian doesn''t enjoy long drives.'),
  (2248, 'english', 'grammar', 'The bus don''t enjoy loud parties.', 'The bus doesn''t enjoy loud parties.'),
  (2249, 'english', 'grammar', 'The cyclist don''t enjoy loud parties.', 'The cyclist doesn''t enjoy loud parties.'),
  (2250, 'english', 'grammar', 'I don''t know nothing about it.', 'I don''t know anything about it.'),
  (2251, 'english', 'grammar', 'The captain don''t enjoy the upcoming trip.', 'The captain doesn''t enjoy the upcoming trip.'),
  (2252, 'english', 'grammar', 'The mayors has finished the task.', 'The mayors have finished the task.'),
  (2253, 'english', 'grammar', 'The children is playing outside.', 'The children are playing outside.'),
  (2254, 'english', 'grammar', 'The toddler have finished the task.', 'The toddler has finished the task.'),
  (2255, 'english', 'grammar', 'The cat have finished the task.', 'The cat has finished the task.'),
  (2256, 'english', 'grammar', 'The pilot don''t enjoy long drives.', 'The pilot doesn''t enjoy long drives.'),
  (2257, 'english', 'grammar', 'My parents is coming over.', 'My parents are coming over.'),
  (2258, 'english', 'grammar', 'The athletes has finished the task.', 'The athletes have finished the task.'),
  (2259, 'english', 'grammar', 'Our friend have finished the task.', 'Our friend has finished the task.'),
  (2260, 'english', 'grammar', 'The inventor don''t enjoy crowded rooms.', 'The inventor doesn''t enjoy crowded rooms.'),
  (2261, 'english', 'grammar', 'She isn''t going nowhere tonight.', 'She isn''t going anywhere tonight.'),
  (2262, 'english', 'grammar', 'The vet go to work every day.', 'The vet goes to work every day.'),
  (2263, 'english', 'grammar', 'She sings beautiful.', 'She sings beautifully.'),
  (2264, 'english', 'grammar', 'The children behaved bad.', 'The children behaved badly.'),
  (2265, 'english', 'grammar', 'The barista don''t enjoy the new policy.', 'The barista doesn''t enjoy the new policy.'),
  (2266, 'english', 'grammar', 'He did the job perfect.', 'He did the job perfectly.'),
  (2267, 'english', 'grammar', 'The cats goes to work every day.', 'The cats go to work every day.'),
  (2268, 'english', 'grammar', 'The fish has finished the task.', 'The fish have finished the task.'),
  (2269, 'english', 'grammar', 'My cousins goes to work every day.', 'My cousins go to work every day.'),
  (2270, 'english', 'grammar', 'The organizations has finished the task.', 'The organizations have finished the task.'),
  (2271, 'english', 'grammar', 'The fish go to work every day.', 'The fish goes to work every day.'),
  (2272, 'english', 'grammar', 'The cat don''t enjoy the morning routine.', 'The cat doesn''t enjoy the morning routine.'),
  (2273, 'english', 'grammar', 'The buses has finished the task.', 'The buses have finished the task.'),
  (2274, 'english', 'grammar', 'He didn''t have no reason to leave.', 'He didn''t have any reason to leave.'),
  (2275, 'english', 'grammar', 'Everyone are invited to the party.', 'Everyone is invited to the party.'),
  (2276, 'english', 'grammar', 'Your right about that.', 'You''re right about that.'),
  (2277, 'english', 'grammar', 'My uncles doesn''t enjoy the noise.', 'My uncles don''t enjoy the noise.'),
  (2278, 'english', 'grammar', 'The cats doesn''t enjoy the noise.', 'The cats don''t enjoy the noise.'),
  (2279, 'english', 'grammar', 'He drives careless.', 'He drives carelessly.'),
  (2280, 'english', 'grammar', 'He don''t have no friends here.', 'He doesn''t have any friends here.'),
  (2281, 'english', 'grammar', 'The technician don''t enjoy crowded rooms.', 'The technician doesn''t enjoy crowded rooms.'),
  (2282, 'english', 'grammar', 'The buses doesn''t enjoy the noise.', 'The buses don''t enjoy the noise.'),
  (2283, 'english', 'grammar', 'The vet don''t enjoy late nights.', 'The vet doesn''t enjoy late nights.'),
  (2284, 'english', 'grammar', 'The tailors doesn''t enjoy the noise.', 'The tailors don''t enjoy the noise.'),
  (2285, 'english', 'grammar', 'They was swimming all day.', 'They were swimming all day.'),
  (2286, 'english', 'grammar', 'I have wrote a letter to her.', 'I have written a letter to her.'),
  (2287, 'english', 'grammar', 'The bus go to work every day.', 'The bus goes to work every day.'),
  (2288, 'english', 'grammar', 'The dog barked loud.', 'The dog barked loudly.'),
  (2289, 'english', 'grammar', 'The historians doesn''t enjoy the noise.', 'The historians don''t enjoy the noise.'),
  (2290, 'english', 'grammar', 'My cousins has finished the task.', 'My cousins have finished the task.'),
  (2291, 'english', 'grammar', 'We have spoke about this before.', 'We have spoken about this before.'),
  (2292, 'english', 'grammar', 'The mayor don''t enjoy the new policy.', 'The mayor doesn''t enjoy the new policy.'),
  (2293, 'english', 'grammar', 'The organizations doesn''t enjoy the noise.', 'The organizations don''t enjoy the noise.'),
  (2294, 'english', 'grammar', 'The vet have finished the task.', 'The vet has finished the task.'),
  (2295, 'english', 'grammar', 'The tailor have finished the task.', 'The tailor has finished the task.'),
  (2296, 'english', 'grammar', 'The puppies goes to work every day.', 'The puppies go to work every day.'),
  (2297, 'english', 'grammar', 'The fish don''t enjoy the final exam.', 'The fish doesn''t enjoy the final exam.'),
  (2298, 'english', 'grammar', 'The keys is missing.', 'The keys are missing.'),
  (2299, 'english', 'grammar', 'The pilots goes to work every day.', 'The pilots go to work every day.'),
  (2300, 'english', 'grammar', 'The professor have finished the task.', 'The professor has finished the task.'),
  (2301, 'english', 'grammar', 'The organization have finished the task.', 'The organization has finished the task.'),
  (2302, 'english', 'grammar', 'My cousin go to work every day.', 'My cousin goes to work every day.'),
  (2303, 'english', 'grammar', 'The pilot have finished the task.', 'The pilot has finished the task.'),
  (2304, 'english', 'grammar', 'The mayors doesn''t enjoy the noise.', 'The mayors don''t enjoy the noise.'),
  (2305, 'english', 'grammar', 'The books is on the shelf.', 'The books are on the shelf.'),
  (2306, 'english', 'grammar', 'The toddlers has finished the task.', 'The toddlers have finished the task.'),
  (2307, 'english', 'grammar', 'The technicians goes to work every day.', 'The technicians go to work every day.'),
  (2308, 'english', 'grammar', 'They finished the race quick.', 'They finished the race quickly.'),
  (2309, 'english', 'grammar', 'He walked slow down the hall.', 'He walked slowly down the hall.'),
  (2310, 'english', 'grammar', 'The fish have finished the task.', 'The fish has finished the task.'),
  (2311, 'english', 'grammar', 'The cyclists has finished the task.', 'The cyclists have finished the task.'),
  (2312, 'english', 'grammar', 'The novelists doesn''t enjoy the noise.', 'The novelists don''t enjoy the noise.'),
  (2313, 'english', 'grammar', 'He has took the wrong turn.', 'He has taken the wrong turn.'),
  (2314, 'english', 'grammar', 'Whose coming to the party tonight?', 'Who''s coming to the party tonight?'),
  (2315, 'english', 'grammar', 'The cyclist have finished the task.', 'The cyclist has finished the task.'),
  (2316, 'english', 'grammar', 'The surgeon don''t enjoy bright colors.', 'The surgeon doesn''t enjoy bright colors.'),
  (2317, 'english', 'grammar', 'The professors has finished the task.', 'The professors have finished the task.'),
  (2318, 'english', 'grammar', 'Its time to go.', 'It''s time to go.'),
  (2319, 'english', 'grammar', 'The athlete don''t enjoy the new policy.', 'The athlete doesn''t enjoy the new policy.'),
  (2320, 'english', 'grammar', 'She spoke soft during the meeting.', 'She spoke softly during the meeting.'),
  (2321, 'english', 'grammar', 'The sculptors doesn''t enjoy the noise.', 'The sculptors don''t enjoy the noise.'),
  (2322, 'english', 'grammar', 'The novelists has finished the task.', 'The novelists have finished the task.'),
  (2323, 'english', 'grammar', 'She smiled happy.', 'She smiled happily.'),
  (2324, 'english', 'grammar', 'My cousin have finished the task.', 'My cousin has finished the task.'),
  (2325, 'english', 'grammar', 'Our friend don''t enjoy the morning routine.', 'Our friend doesn''t enjoy the morning routine.'),
  (2326, 'english', 'grammar', 'They worked quiet.', 'They worked quietly.'),
  (2327, 'english', 'grammar', 'The cyclists doesn''t enjoy the noise.', 'The cyclists don''t enjoy the noise.'),
  (2328, 'english', 'grammar', 'They don''t want no trouble.', 'They don''t want any trouble.'),
  (2329, 'english', 'grammar', 'The novelist have finished the task.', 'The novelist has finished the task.'),
  (2330, 'english', 'grammar', 'The sculptors has finished the task.', 'The sculptors have finished the task.'),
  (2331, 'english', 'grammar', 'The professors doesn''t enjoy the noise.', 'The professors don''t enjoy the noise.'),
  (2332, 'english', 'grammar', 'The pilots doesn''t enjoy the noise.', 'The pilots don''t enjoy the noise.'),
  (2333, 'english', 'grammar', 'The tailor don''t enjoy loud parties.', 'The tailor doesn''t enjoy loud parties.'),
  (2334, 'english', 'grammar', 'The directors has finished the task.', 'The directors have finished the task.')
on conflict (id) do update set
  subject = excluded.subject,
  category = excluded.category,
  prompt = excluded.prompt,
  answer = excluded.answer;

-- ============================================================
-- English · Spelling (332 questions)
-- ============================================================
insert into public.quiz_questions (id, subject, category, prompt, answer) values
  (3001, 'english', 'spelling', 'symptem', 'symptom'),
  (3002, 'english', 'spelling', 'quantaty', 'quantity'),
  (3003, 'english', 'spelling', 'inocculate', 'inoculate'),
  (3004, 'english', 'spelling', 'perfom', 'perform'),
  (3005, 'english', 'spelling', 'fascinatting', 'fascinating'),
  (3006, 'english', 'spelling', 'collegue', 'colleague'),
  (3007, 'english', 'spelling', 'interupt', 'interrupt'),
  (3008, 'english', 'spelling', 'percieve', 'perceive'),
  (3009, 'english', 'spelling', 'visable', 'visible'),
  (3010, 'english', 'spelling', 'nineth', 'ninth'),
  (3011, 'english', 'spelling', 'definately', 'definitely'),
  (3012, 'english', 'spelling', 'thorogh', 'thorough'),
  (3013, 'english', 'spelling', 'wheather', 'weather'),
  (3014, 'english', 'spelling', 'fourty', 'forty'),
  (3015, 'english', 'spelling', 'wich', 'which'),
  (3016, 'english', 'spelling', 'strenght', 'strength'),
  (3017, 'english', 'spelling', 'playright', 'playwright'),
  (3018, 'english', 'spelling', 'tragady', 'tragedy'),
  (3019, 'english', 'spelling', 'whereever', 'wherever'),
  (3020, 'english', 'spelling', 'recipt', 'receipt'),
  (3021, 'english', 'spelling', 'liesure', 'leisure'),
  (3022, 'english', 'spelling', 'persaude', 'persuade'),
  (3023, 'english', 'spelling', 'peculier', 'peculiar'),
  (3024, 'english', 'spelling', 'likelyhood', 'likelihood'),
  (3025, 'english', 'spelling', 'suprise', 'surprise'),
  (3026, 'english', 'spelling', 'loosing', 'losing'),
  (3027, 'english', 'spelling', 'memonto', 'memento'),
  (3028, 'english', 'spelling', 'nickle', 'nickel'),
  (3029, 'english', 'spelling', 'refrence', 'reference'),
  (3030, 'english', 'spelling', 'comparitive', 'comparative'),
  (3031, 'english', 'spelling', 'pronounciation', 'pronunciation'),
  (3032, 'english', 'spelling', 'misspel', 'misspell'),
  (3033, 'english', 'spelling', 'suspicous', 'suspicious'),
  (3034, 'english', 'spelling', 'critisize', 'criticize'),
  (3035, 'english', 'spelling', 'vengance', 'vengeance'),
  (3036, 'english', 'spelling', 'sucess', 'success'),
  (3037, 'english', 'spelling', 'undoubtedley', 'undoubtedly'),
  (3038, 'english', 'spelling', 'existance', 'existence'),
  (3039, 'english', 'spelling', 'villian', 'villain'),
  (3040, 'english', 'spelling', 'payed', 'paid'),
  (3041, 'english', 'spelling', 'questionaire', 'questionnaire'),
  (3042, 'english', 'spelling', 'noticable', 'noticeable'),
  (3043, 'english', 'spelling', 'becuase', 'because'),
  (3044, 'english', 'spelling', 'tremendus', 'tremendous'),
  (3045, 'english', 'spelling', 'shinning', 'shining'),
  (3046, 'english', 'spelling', 'concious', 'conscious'),
  (3047, 'english', 'spelling', 'libary', 'library'),
  (3048, 'english', 'spelling', 'apparant', 'apparent'),
  (3049, 'english', 'spelling', 'omision', 'omission'),
  (3050, 'english', 'spelling', 'useage', 'usage'),
  (3051, 'english', 'spelling', 'succesful', 'successful'),
  (3052, 'english', 'spelling', 'laboratary', 'laboratory'),
  (3053, 'english', 'spelling', 'commitee', 'committee'),
  (3054, 'english', 'spelling', 'writting', 'writing'),
  (3055, 'english', 'spelling', 'irresistable', 'irresistible'),
  (3056, 'english', 'spelling', 'religous', 'religious'),
  (3057, 'english', 'spelling', 'particulary', 'particularly'),
  (3058, 'english', 'spelling', 'gague', 'gauge'),
  (3059, 'english', 'spelling', 'therefor', 'therefore'),
  (3060, 'english', 'spelling', 'principel', 'principle'),
  (3061, 'english', 'spelling', 'zealus', 'zealous'),
  (3062, 'english', 'spelling', 'occassion', 'occasion'),
  (3063, 'english', 'spelling', 'offical', 'official'),
  (3064, 'english', 'spelling', 'wemen', 'women'),
  (3065, 'english', 'spelling', 'aquire', 'acquire'),
  (3066, 'english', 'spelling', 'mysterius', 'mysterious'),
  (3067, 'english', 'spelling', 'regaurd', 'regard'),
  (3068, 'english', 'spelling', 'predictible', 'predictable'),
  (3069, 'english', 'spelling', 'realy', 'really'),
  (3070, 'english', 'spelling', 'liason', 'liaison'),
  (3071, 'english', 'spelling', 'proceedure', 'procedure'),
  (3072, 'english', 'spelling', 'parliment', 'parliament'),
  (3073, 'english', 'spelling', 'stoped', 'stopped'),
  (3074, 'english', 'spelling', 'opertunity', 'opportunity'),
  (3075, 'english', 'spelling', 'occured', 'occurred'),
  (3076, 'english', 'spelling', 'recieve', 'receive'),
  (3077, 'english', 'spelling', 'embarass', 'embarrass'),
  (3078, 'english', 'spelling', 'gaurd', 'guard'),
  (3079, 'english', 'spelling', 'tornament', 'tournament'),
  (3080, 'english', 'spelling', 'usualy', 'usually'),
  (3081, 'english', 'spelling', 'independant', 'independent'),
  (3082, 'english', 'spelling', 'susceptable', 'susceptible'),
  (3083, 'english', 'spelling', 'neighbour', 'neighbor'),
  (3084, 'english', 'spelling', 'millionair', 'millionaire'),
  (3085, 'english', 'spelling', 'commited', 'committed'),
  (3086, 'english', 'spelling', 'magnificant', 'magnificent'),
  (3087, 'english', 'spelling', 'effect', 'affect'),
  (3088, 'english', 'spelling', 'repitition', 'repetition'),
  (3089, 'english', 'spelling', 'stratagy', 'strategy'),
  (3090, 'english', 'spelling', 'morgage', 'mortgage'),
  (3091, 'english', 'spelling', 'familliar', 'familiar'),
  (3092, 'english', 'spelling', 'scenary', 'scenery'),
  (3093, 'english', 'spelling', 'obstacal', 'obstacle'),
  (3094, 'english', 'spelling', 'paralel', 'parallel'),
  (3095, 'english', 'spelling', 'judgement', 'judgment'),
  (3096, 'english', 'spelling', 'exagerate', 'exaggerate'),
  (3097, 'english', 'spelling', 'propoganda', 'propaganda'),
  (3098, 'english', 'spelling', 'rythm', 'rhythm'),
  (3099, 'english', 'spelling', 'medievel', 'medieval'),
  (3100, 'english', 'spelling', 'competant', 'competent'),
  (3101, 'english', 'spelling', 'athelete', 'athlete'),
  (3102, 'english', 'spelling', 'aquaintance', 'acquaintance'),
  (3103, 'english', 'spelling', 'feirce', 'fierce'),
  (3104, 'english', 'spelling', 'recomend', 'recommend'),
  (3105, 'english', 'spelling', 'skying', 'skiing'),
  (3106, 'english', 'spelling', 'lisence', 'license'),
  (3107, 'english', 'spelling', 'nuisence', 'nuisance'),
  (3108, 'english', 'spelling', 'temporery', 'temporary'),
  (3109, 'english', 'spelling', 'hierachy', 'hierarchy'),
  (3110, 'english', 'spelling', 'loniless', 'loneliness'),
  (3111, 'english', 'spelling', 'wholey', 'wholly'),
  (3112, 'english', 'spelling', 'tendancy', 'tendency'),
  (3113, 'english', 'spelling', 'acheive', 'achieve'),
  (3114, 'english', 'spelling', 'spontanious', 'spontaneous'),
  (3115, 'english', 'spelling', 'Febuary', 'February'),
  (3116, 'english', 'spelling', 'equiptment', 'equipment'),
  (3117, 'english', 'spelling', 'correspondance', 'correspondence'),
  (3118, 'english', 'spelling', 'severel', 'several'),
  (3119, 'english', 'spelling', 'unfortunatly', 'unfortunately'),
  (3120, 'english', 'spelling', 'statistic', 'statistics'),
  (3121, 'english', 'spelling', 'goverment', 'government'),
  (3122, 'english', 'spelling', 'definate', 'definite'),
  (3123, 'english', 'spelling', 'vehical', 'vehicle'),
  (3124, 'english', 'spelling', 'surrond', 'surround'),
  (3125, 'english', 'spelling', 'usible', 'usable'),
  (3126, 'english', 'spelling', 'prominant', 'prominent'),
  (3127, 'english', 'spelling', 'satelite', 'satellite'),
  (3128, 'english', 'spelling', 'sargent', 'sergeant'),
  (3129, 'english', 'spelling', 'catagory', 'category'),
  (3130, 'english', 'spelling', 'arguement', 'argument'),
  (3131, 'english', 'spelling', 'intresting', 'interesting'),
  (3132, 'english', 'spelling', 'passtime', 'pastime'),
  (3133, 'english', 'spelling', 'personel', 'personnel'),
  (3134, 'english', 'spelling', 'pleasent', 'pleasant'),
  (3135, 'english', 'spelling', 'Wendsday', 'Wednesday'),
  (3136, 'english', 'spelling', 'veiw', 'view'),
  (3137, 'english', 'spelling', 'prefered', 'preferred'),
  (3138, 'english', 'spelling', 'perspiretion', 'perspiration'),
  (3139, 'english', 'spelling', 'moveable', 'movable'),
  (3140, 'english', 'spelling', 'valuble', 'valuable'),
  (3141, 'english', 'spelling', 'optimisim', 'optimism'),
  (3142, 'english', 'spelling', 'variaty', 'variety'),
  (3143, 'english', 'spelling', 'tyrany', 'tyranny'),
  (3144, 'english', 'spelling', 'persistant', 'persistent'),
  (3145, 'english', 'spelling', 'experiance', 'experience'),
  (3146, 'english', 'spelling', 'permanant', 'permanent'),
  (3147, 'english', 'spelling', 'violance', 'violence'),
  (3148, 'english', 'spelling', 'pamphlit', 'pamphlet'),
  (3149, 'english', 'spelling', 'changable', 'changeable'),
  (3150, 'english', 'spelling', 'decieve', 'deceive'),
  (3151, 'english', 'spelling', 'indispensible', 'indispensable'),
  (3152, 'english', 'spelling', 'quee', 'queue'),
  (3153, 'english', 'spelling', 'wellcome', 'welcome'),
  (3154, 'english', 'spelling', 'urgant', 'urgent'),
  (3155, 'english', 'spelling', 'outragous', 'outrageous'),
  (3156, 'english', 'spelling', 'secretery', 'secretary'),
  (3157, 'english', 'spelling', 'unforseen', 'unforeseen'),
  (3158, 'english', 'spelling', 'immediatly', 'immediately'),
  (3159, 'english', 'spelling', 'alot', 'a lot'),
  (3160, 'english', 'spelling', 'posess', 'possess'),
  (3161, 'english', 'spelling', 'ninty', 'ninety'),
  (3162, 'english', 'spelling', 'socity', 'society'),
  (3163, 'english', 'spelling', 'miscelaneous', 'miscellaneous'),
  (3164, 'english', 'spelling', 'yeild', 'yield'),
  (3165, 'english', 'spelling', 'pneumonya', 'pneumonia'),
  (3166, 'english', 'spelling', 'dissapoint', 'disappoint'),
  (3167, 'english', 'spelling', 'improev', 'improve'),
  (3168, 'english', 'spelling', 'lengthh', 'length'),
  (3169, 'english', 'spelling', 'machnie', 'machine'),
  (3170, 'english', 'spelling', 'dcision', 'decision'),
  (3171, 'english', 'spelling', 'ceiliing', 'ceiling'),
  (3172, 'english', 'spelling', 'edsperate', 'desperate'),
  (3173, 'english', 'spelling', 'preseence', 'presence'),
  (3174, 'english', 'spelling', 'mmuscle', 'muscle'),
  (3175, 'english', 'spelling', 'mnimum', 'minimum'),
  (3176, 'english', 'spelling', 'accidantally', 'accidentally'),
  (3177, 'english', 'spelling', 'protcet', 'protect'),
  (3178, 'english', 'spelling', 'adolesecnt', 'adolescent'),
  (3179, 'english', 'spelling', 'connnect', 'connect'),
  (3180, 'english', 'spelling', 'contriubte', 'contribute'),
  (3181, 'english', 'spelling', 'immenes', 'immense'),
  (3182, 'english', 'spelling', 'complte', 'complete'),
  (3183, 'english', 'spelling', 'ppurchase', 'purchase'),
  (3184, 'english', 'spelling', 'oprate', 'operate'),
  (3185, 'english', 'spelling', 'identityy', 'identity'),
  (3186, 'english', 'spelling', 'leaarning', 'learning'),
  (3187, 'english', 'spelling', 'hhappening', 'happening'),
  (3188, 'english', 'spelling', 'innformation', 'information'),
  (3189, 'english', 'spelling', 'passsage', 'passage'),
  (3190, 'english', 'spelling', 'vegetble', 'vegetable'),
  (3191, 'english', 'spelling', 'imoprtant', 'important'),
  (3192, 'english', 'spelling', 'pressident', 'president'),
  (3193, 'english', 'spelling', 'effciient', 'efficient'),
  (3194, 'english', 'spelling', 'medicien', 'medicine'),
  (3195, 'english', 'spelling', 'advetrisement', 'advertisement'),
  (3196, 'english', 'spelling', 'nnarrow', 'narrow'),
  (3197, 'english', 'spelling', 'bbeginning', 'beginning'),
  (3198, 'english', 'spelling', 'leegant', 'elegant'),
  (3199, 'english', 'spelling', 'mlitary', 'military'),
  (3200, 'english', 'spelling', 'peoplle', 'people'),
  (3201, 'english', 'spelling', 'aaccurate', 'accurate'),
  (3202, 'english', 'spelling', 'pleasatn', 'pleasant'),
  (3203, 'english', 'spelling', 'famly', 'family'),
  (3204, 'english', 'spelling', 'pacckage', 'package'),
  (3205, 'english', 'spelling', 'increse', 'increase'),
  (3206, 'english', 'spelling', 'inddustry', 'industry'),
  (3207, 'english', 'spelling', 'persnal', 'personal'),
  (3208, 'english', 'spelling', 'beaautiful', 'beautiful'),
  (3209, 'english', 'spelling', 'lectrue', 'lecture'),
  (3210, 'english', 'spelling', 'directoin', 'direction'),
  (3211, 'english', 'spelling', 'opsitive', 'positive'),
  (3212, 'english', 'spelling', 'matterial', 'material'),
  (3213, 'english', 'spelling', 'concentraate', 'concentrate'),
  (3214, 'english', 'spelling', 'discipliine', 'discipline'),
  (3215, 'english', 'spelling', 'analzye', 'analyze'),
  (3216, 'english', 'spelling', 'honst', 'honest'),
  (3217, 'english', 'spelling', 'naturall', 'natural'),
  (3218, 'english', 'spelling', 'influencce', 'influence'),
  (3219, 'english', 'spelling', 'provdie', 'provide'),
  (3220, 'english', 'spelling', 'proudce', 'produce'),
  (3221, 'english', 'spelling', 'genine', 'genuine'),
  (3222, 'english', 'spelling', 'xeample', 'example'),
  (3223, 'english', 'spelling', 'eveyrbody', 'everybody'),
  (3224, 'english', 'spelling', 'prooperty', 'property'),
  (3225, 'english', 'spelling', 'wonderufl', 'wonderful'),
  (3226, 'english', 'spelling', 'felxible', 'flexible'),
  (3227, 'english', 'spelling', 'faavorite', 'favorite'),
  (3228, 'english', 'spelling', 'insurnce', 'insurance'),
  (3229, 'english', 'spelling', 'cnfidence', 'confidence'),
  (3230, 'english', 'spelling', 'eagr', 'eager'),
  (3231, 'english', 'spelling', 'islaand', 'island'),
  (3232, 'english', 'spelling', 'prrimary', 'primary'),
  (3233, 'english', 'spelling', 'generrous', 'generous'),
  (3234, 'english', 'spelling', 'poistion', 'position'),
  (3235, 'english', 'spelling', 'educationn', 'education'),
  (3236, 'english', 'spelling', 'pirsoner', 'prisoner'),
  (3237, 'english', 'spelling', 'prmoise', 'promise'),
  (3238, 'english', 'spelling', 'progrress', 'progress'),
  (3239, 'english', 'spelling', 'ooccasion', 'occasion'),
  (3240, 'english', 'spelling', 'severl', 'several'),
  (3241, 'english', 'spelling', 'saandwich', 'sandwich'),
  (3242, 'english', 'spelling', 'excat', 'exact'),
  (3243, 'english', 'spelling', 'idsaster', 'disaster'),
  (3244, 'english', 'spelling', 'quesstion', 'question'),
  (3245, 'english', 'spelling', 'instrucct', 'instruct'),
  (3246, 'english', 'spelling', 'proejct', 'project'),
  (3247, 'english', 'spelling', 'appreicate', 'appreciate'),
  (3248, 'english', 'spelling', 'mlilion', 'million'),
  (3249, 'english', 'spelling', 'entertani', 'entertain'),
  (3250, 'english', 'spelling', 'handlle', 'handle'),
  (3251, 'english', 'spelling', 'brillaint', 'brilliant'),
  (3252, 'english', 'spelling', 'cicrumstance', 'circumstance'),
  (3253, 'english', 'spelling', 'opinon', 'opinion'),
  (3254, 'english', 'spelling', 'graddual', 'gradual'),
  (3255, 'english', 'spelling', 'librty', 'liberty'),
  (3256, 'english', 'spelling', 'mentin', 'mention'),
  (3257, 'english', 'spelling', 'gravvity', 'gravity'),
  (3258, 'english', 'spelling', 'histoory', 'history'),
  (3259, 'english', 'spelling', 'thhough', 'though'),
  (3260, 'english', 'spelling', 'differnet', 'different'),
  (3261, 'english', 'spelling', 'aabsence', 'absence'),
  (3262, 'english', 'spelling', 'outsiide', 'outside'),
  (3263, 'english', 'spelling', 'rpogram', 'program'),
  (3264, 'english', 'spelling', 'poocket', 'pocket'),
  (3265, 'english', 'spelling', 'paragrahp', 'paragraph'),
  (3266, 'english', 'spelling', 'ntaion', 'nation'),
  (3267, 'english', 'spelling', 'troubble', 'trouble'),
  (3268, 'english', 'spelling', 'involvee', 'involve'),
  (3269, 'english', 'spelling', 'employeee', 'employee'),
  (3270, 'english', 'spelling', 'qualityy', 'quality'),
  (3271, 'english', 'spelling', 'prretend', 'pretend'),
  (3272, 'english', 'spelling', 'prpeare', 'prepare'),
  (3273, 'english', 'spelling', 'pllanet', 'planet'),
  (3274, 'english', 'spelling', 'reaason', 'reason'),
  (3275, 'english', 'spelling', 'messgae', 'message'),
  (3276, 'english', 'spelling', 'guses', 'guess'),
  (3277, 'english', 'spelling', 'nistance', 'instance'),
  (3278, 'english', 'spelling', 'picturre', 'picture'),
  (3279, 'english', 'spelling', 'imaagine', 'imagine'),
  (3280, 'english', 'spelling', 'sepcial', 'special'),
  (3281, 'english', 'spelling', 'disccover', 'discover'),
  (3282, 'english', 'spelling', 'hansdome', 'handsome'),
  (3283, 'english', 'spelling', 'frieend', 'friend'),
  (3284, 'english', 'spelling', 'lnguage', 'language'),
  (3285, 'english', 'spelling', 'conveinent', 'convenient'),
  (3286, 'english', 'spelling', 'throughh', 'through'),
  (3287, 'english', 'spelling', 'ppattern', 'pattern'),
  (3288, 'english', 'spelling', 'frequeent', 'frequent'),
  (3289, 'english', 'spelling', 'aannual', 'annual'),
  (3290, 'english', 'spelling', 'quentity', 'quantity'),
  (3291, 'english', 'spelling', 'yestedray', 'yesterday'),
  (3292, 'english', 'spelling', 'chooclate', 'chocolate'),
  (3293, 'english', 'spelling', 'kitchhen', 'kitchen'),
  (3294, 'english', 'spelling', 'physiical', 'physical'),
  (3295, 'english', 'spelling', 'invetnion', 'invention'),
  (3296, 'english', 'spelling', 'oriignal', 'original'),
  (3297, 'english', 'spelling', 'orgainze', 'organize'),
  (3298, 'english', 'spelling', 'investigatee', 'investigate'),
  (3299, 'english', 'spelling', 'inittial', 'initial'),
  (3300, 'english', 'spelling', 'nerovus', 'nervous'),
  (3301, 'english', 'spelling', 'llocation', 'location'),
  (3302, 'english', 'spelling', 'columnn', 'column'),
  (3303, 'english', 'spelling', 'popluar', 'popular'),
  (3304, 'english', 'spelling', 'innoecnt', 'innocent'),
  (3305, 'english', 'spelling', 'insttrument', 'instrument'),
  (3306, 'english', 'spelling', 'nationaal', 'national'),
  (3307, 'english', 'spelling', 'ccommunity', 'community'),
  (3308, 'english', 'spelling', 'porbably', 'probably'),
  (3309, 'english', 'spelling', 'deliciouss', 'delicious'),
  (3310, 'english', 'spelling', 'guiadnce', 'guidance'),
  (3311, 'english', 'spelling', 'lauughter', 'laughter'),
  (3312, 'english', 'spelling', 'howevre', 'however'),
  (3313, 'english', 'spelling', 'unusula', 'unusual'),
  (3314, 'english', 'spelling', 'prfect', 'perfect'),
  (3315, 'english', 'spelling', 'prdouct', 'product'),
  (3316, 'english', 'spelling', 'expplanation', 'explanation'),
  (3317, 'english', 'spelling', 'thoughht', 'thought'),
  (3318, 'english', 'spelling', 'itnelligent', 'intelligent'),
  (3319, 'english', 'spelling', 'accompanyy', 'accompany'),
  (3320, 'english', 'spelling', 'llisten', 'listen'),
  (3321, 'english', 'spelling', 'comfortabble', 'comfortable'),
  (3322, 'english', 'spelling', 'coollect', 'collect'),
  (3323, 'english', 'spelling', 'poossible', 'possible'),
  (3324, 'english', 'spelling', 'rmeember', 'remember'),
  (3325, 'english', 'spelling', 'autunm', 'autumn'),
  (3326, 'english', 'spelling', 'sciennce', 'science'),
  (3327, 'english', 'spelling', 'oppositee', 'opposite'),
  (3328, 'english', 'spelling', 'omvement', 'movement'),
  (3329, 'english', 'spelling', 'cnogratulate', 'congratulate'),
  (3330, 'english', 'spelling', 'knowledeg', 'knowledge'),
  (3331, 'english', 'spelling', 'healthhy', 'healthy'),
  (3332, 'english', 'spelling', 'describbe', 'describe')
on conflict (id) do update set
  subject = excluded.subject,
  category = excluded.category,
  prompt = excluded.prompt,
  answer = excluded.answer;
